### SIGNUPS

### valid email
POST http://localhost:3000/signup
Content-Type: application/json

{
    "name": "Ace Ventura",
    "email": "aceventura@gmail.com",
    "password": "password"
}

### invalid email
POST http://localhost:3000/signup
Content-Type: application/json

{
    "name": "Johnny Appleseed",
    "email": "appleseed",
    "password": "password"
}

###
POST https://web-app-liverton.herokuapp.com/signup
Content-Type: application/json

{
    "name": "Mark Ronson",
    "email": "markothy@gmail.com",
    "password": "password"
}

### LOGINS

### valid email
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "aceventura@gmail.com",
    "password": "password"
}

### email does not exist
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "reqres@gmail.com",
    "password": "passsdord"
}

### validated GET
GET http://localhost:3000/chat
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTlhOWMzMmRmNmNhNDBmMDc4NDZjZmUiLCJpYXQiOjE1ODczNTI2MTl9.mqGo_UTSSqflQiG-DTlenWxtJbh2JumSnv8B_RURGAo

### unvalidated GET
GET http://localhost:3000/chat